### ISSUE TITLE
minimizing game leads to crash

### ISSUE THREAD

**Issue by kampffrosch94** [darthdeus/comfy#12]
encountered on an up to date windows 10

steps to reproduce:
- `cargo run --example text`
- minimize window

Error message:
```
[ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
The application panicked (crashed).
Message:  wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `egui Render Encoder`
    In a set_viewport command
    Viewport width 0 and/or height 0 are less than or equal to 0
```

**Comment by Kenkron** [comment]
I notice that there's a check for 0 width and height, but the egui window resize isn't in it. Maybe it should be. https://github.com/darthdeus/comfy/blob/b9e1131a05ad60b99aead595c9fb46982f219702/comfy-wgpu/src/renderer.rs#L1641

**Comment by LevBeta** [comment]
As mentioned by @Kenkron , the resize function in the renderer currently checks if the width and height are higher than 0 before attempting to resize the window. However, there's an issue where we unintentionally try to resize the window to dimensions (0, 0), which is not supported.

To properly minimize the window, we should use the following method:

`self.window.set_minimized(true);`

I think that the call to minimize the window should not be placed directly inside the `resize` function. It would be more maintainable and clear to create a dedicated function specifically for handling window minimize actions. Unfortunately, since I'm not very familiar with the codebase of this project,

**Comment by darthdeus** [comment]
> To properly minimize the window, we should use the following method:
> self.window.set_minimized(true);

Hmm, I'm not sure if I understand but isn't this for when we want to minimize the window programmatically, as opposed to the user clicking the minimize button?

I can't test this atm as I'm stuck on Linux/MacOS, but I'll look into it on windows a bit later.

**Comment by LevBeta** [comment]
> Hmm, I'm not sure if I understand but isn't this for when we want to minimize the window programmatically, as opposed to the user clicking the minimize button?

I was actually mistaken in my previous comment. I thought that we would need to minimize the window programmatically, but it turned out that egui was actually managing window minimization on its own. The issue arose when the WindowEvent called the resize function and set the values of width and height to 0, resulting in a panic in the Egui renderer.

I have submitted a PR to "fix" this issue. However, it's important to note that after this fix, the draw function no longer executes when the window is minimized, as calling Surface::get_current_texture returns an error in that state.

Maybe it is possible to get a way around that if it is really needed to draw when minimized

**Comment by darthdeus** [comment]
Closing as #22 fixes it and was merged.
