### ISSUE TITLE
Timed draw example is broken

### ISSUE THREAD

**Issue by darthdeus** [darthdeus/comfy#34]

**Comment by LevBeta** [comment]
If this issue is refered to "Message:  already mutably borrowed", which is the same as my last comment of the #33 

The problem is actually on the `draw_params` struct from the `renderer_update` fn.

Which tries to do `&mut game_config_mut()`, which is technically `already mutably borrowed`

With some super messy code for verify if the bug comes from here (THIS IS NOT A SOLUTION), i could "fix" this

![image](https://github.com/darthdeus/comfy/assets/105949605/a41a1f65-284b-42d1-bb1c-aed4022b5ea6)

**Comment by darthdeus** [comment]
The borrow checker issue is unrelated to this and broke all examples, but it's now fixed on master.
