### ISSUE TITLE
Add `wayland` support

### ISSUE THREAD

**Issue by RobWalt** [darthdeus/comfy#51]
Currently `comfy-wgpu` only supports the x11 backend for `winit`. 

After changing that to `wayland`, `comfy` runs out of the box on `wayland` without further adjustments (at least the `circle` example)

Are there any plans on providing wayland support via a feature flag or anything similar? I'd love to get your input on this. I can even open a PR for the changes once the decision was made.

**Comment by darthdeus** [comment]
If I understand correctly it should just work with `--features winit/wayland` right? I'm totally fine with having a `wayland = ["winit/wayland"]` flag in comfy that is not enabled by default. The reason I removed it is last time I profiled compile times some of the wayland stuff was contributing in a non-trivial way.

That being said, it definitely makes sense to have a feature flag. I think it should also be enabled in the `ci-release` feature flag, as in `ci-release = ["comfy-core/ci-release", "comfy-wgpu/ci-release"]` becoming `ci-release = ["comfy-core/ci-release", "comfy-wgpu/ci-release", "wayland"]` or something of the sort, so that release builds always have this.

The feature flag `ci-release` is something that's currently undocumented, tho the way Comfy is setup (and the way we use it) is this is a flag we enable on builds that get uploaded to Steam/Itch and controls a bunch of things.

Ideally this should be the "this is a release build for actual players" flag that enables/disables everything that makes sense, which should mean "maximum platform support" and "disabling debug stuff" (for example hot reloading of shaders gets disabled with this flag).

Feel free to make the PR if you want :)
